apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
   name: nghpauto
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: DEployment
    name: mydeploument
  minReplicas: 2
  maxReplicas: 3
  mertrcis:
    - type: Resource
      resource:
          name: cpu
          target:
             type: Utilization
             averageUtilization: 20

