apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvpod
spec:
   capacity:
     storage: 1Gi
   accessModes:
      - ReadWriteOnce
   persistentVolunmeReclaimPolicy: Retain
   hostPath:
      path: /mydata

pvc.yml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvcpod
spec:
   resources:
      requests:
        storage: 1Gi
   accessModes:
      - ReadWriteOnce
